<a href="https://colab.research.google.com/github/abubakirovx/ai-foundation/blob/main/Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd

In [ ]:
myDataSet={
    "cars":["BMW","MERC","FORD","Tesla","Ferrari","Volvo","GM"],
    "counts":[23,54,76,120,32,12,34]
}
df=pd.DataFrame(myDataSet)
print(df)

      cars  counts
0      BMW      23
1     MERC      54
2     FORD      76
3    Tesla     120
4  Ferrari      32
5    Volvo      12
6       GM      34

In [ ]:
df.head() #default 5 rows

      cars  counts
0      BMW      23
1     MERC      54
2     FORD      76
3    Tesla     120
4  Ferrari      32

In [ ]:
df.tail(3) #default 5 rows (desc)

      cars  counts
4  Ferrari      32
5    Volvo      12
6       GM      34

In [ ]:
df.columns

Index(['cars', 'counts'], dtype='object')

In [ ]:
df.dtypes

cars      object
counts     int64
dtype: object

In [ ]:
print(df)

      cars  counts
0      BMW      23
1     MERC      54
2     FORD      76
3    Tesla     120
4  Ferrari      32
5    Volvo      12
6       GM      34

In [ ]:
df.describe()

           counts
count    7.000000
mean    50.142857
std     37.293559
min     12.000000
25%     27.500000
50%     34.000000
75%     65.000000
max    120.000000

In [ ]:
df.iloc[3:]

      cars  counts
3    Tesla     120
4  Ferrari      32
5    Volvo      12
6       GM      34

In [ ]:
df.loc[2:4,"cars"]

2       FORD
3      Tesla
4    Ferrari
Name: cars, dtype: object

In [ ]:
print(df)

      cars  counts
0      BMW      23
1     MERC      54
2     FORD      76
3    Tesla     120
4  Ferrari      32
5    Volvo      12
6       GM      34

In [ ]:
df["counts"]>60

0    False
1    False
2     True
3     True
4    False
5    False
6    False
Name: counts, dtype: bool

In [ ]:
df[df["counts"]>60]

    cars  counts
2   FORD      76
3  Tesla     120

In [ ]:
df[df["cars"]=="Tesla"]

    cars  counts
3  Tesla     120

In [ ]:
df["cars"]=="Tesla"

0    False
1    False
2    False
3     True
4    False
5    False
6    False
Name: cars, dtype: bool

In [ ]:
df.mean(numeric_only=True)

counts    50.142857
dtype: float64

In [ ]:
df['counts'].mean()

np.float64(50.142857142857146)

In [ ]:
df.sum()

cars      BMWMERCFORDTeslaFerrariVolvoGM
counts                               351
dtype: object

In [ ]:
df.min()

cars      BMW
counts     12
dtype: object

In [ ]:
df.max()

cars      Volvo
counts      120
dtype: object

In [ ]:
df.median(numeric_only=True)

counts    34.0
dtype: float64

In [ ]:
df.count()

cars      7
counts    7
dtype: int64

In [ ]:
df.std(numeric_only=True)

counts    37.293559
dtype: float64

In [4]:
df_with_missing={
  "cars":["BMW","MERC",None,"Tesla","Ferrari",None,"GM"],
    "counts":[23,54,76,None,32,12,None]
}
df_missing=pd.DataFrame(df_with_missing)
print(df_missing)

      cars  counts
0      BMW    23.0
1     MERC    54.0
2     None    76.0
3    Tesla     NaN
4  Ferrari    32.0
5     None    12.0
6       GM     NaN

In [6]:
df_missing.isnull().sum()

cars      2
counts    2
dtype: int64

In [8]:
df_missing.dropna(how="all")

      cars  counts
0      BMW    23.0
1     MERC    54.0
2     None    76.0
3    Tesla     NaN
4  Ferrari    32.0
5     None    12.0
6       GM     NaN

In [9]:
df_missing.dropna(subset="counts")

      cars  counts
0      BMW    23.0
1     MERC    54.0
2     None    76.0
4  Ferrari    32.0
5     None    12.0

In [10]:
df_missing.dropna(subset="cars")

      cars  counts
0      BMW    23.0
1     MERC    54.0
3    Tesla     NaN
4  Ferrari    32.0
6       GM     NaN

In [11]:
df_missing.fillna({"cars":"unknown","counts":0})

      cars  counts
0      BMW    23.0
1     MERC    54.0
2  unknown    76.0
3    Tesla     0.0
4  Ferrari    32.0
5  unknown    12.0
6       GM     0.0

In [15]:
df = pd.read_csv("Titanic-Dataset.csv")

df.head()
# df = pd.read_excel("Titanic-Dataset.xlsx")
# df = pd.read_json("Titanic-Dataset.json")

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [16]:
df.tail()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.00,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.00,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

In [19]:
df.to_excel("test.xlsx")
df = pd.read_excel("test.xlsx")
df.head()

,Unnamed: 0.1,Unnamed: 0,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,0,0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,1,1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,2,2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,3,3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,4,4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [22]:
cars=pd.Series(["BMW","Volvo"])
print(cars)

0      BMW
1    Volvo
dtype: object